package com.tenjava.entries.mncat77.t3;

import com.tenjava.entries.mncat77.t3.generator.FakeChunkGenerator;
import com.tenjava.entries.mncat77.t3.generator.HardcoreChunkGenerator;
import java.lang.reflect.Field;
import net.minecraft.server.v1_7_R3.ChunkProviderServer;
import net.minecraft.server.v1_7_R3.MinecraftServer;
import net.minecraft.server.v1_7_R3.WorldServer;
import org.bukkit.Bukkit;
import org.bukkit.generator.ChunkGenerator;
import org.bukkit.plugin.java.JavaPlugin;

public class TenJava extends JavaPlugin {

    private int taskId;

    //Stupid Bukkit doesn't let us inject our chunkprovider before the spawn is generated, so we let the spawn be generated by this fake chunk generator
    @Override
    public ChunkGenerator getDefaultWorldGenerator(String worldName, String id) {
        return new FakeChunkGenerator();
    }

    @Override
    public void onEnable() {
        //Replace the world's chunkprovider with our's
        taskId = Bukkit.getScheduler().scheduleSyncRepeatingTask(this, new Runnable() {
            @Override
            public void run() {
                try {
                    WorldServer w = MinecraftServer.getServer().getWorldServer(0);
                    Field f = ChunkProviderServer.class.getDeclaredField("f");
                    f.setAccessible(true);
                    HardcoreChunkGenerator gen = new HardcoreChunkGenerator(w);
                    w.generator = gen;
                    w.chunkProviderServer.chunkProvider = gen;
                    Bukkit.getScheduler().cancelTask(taskId);
                }
                catch(Exception e) {
                }
            }
        }, 0L, 1L);
    }
}
